on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

name: "CI"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --all-features --all-targets

      - name: Build
        run: cargo build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Unit Tests
        run: cargo test

  lint:
    name: Lint (clippy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

        # strict version that does not allow _any_ wclippy warnings to pass
      # - run: cargo clippy -- -D warnings
        # allows warnings to pass (but still not errors)
      - run: cargo clippy --all-features --all-targets

  format:
    name: Format (rustfmt)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all -- --check
